import re
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

ADVISORY_TRIGGER_PHRASES = [
    "i recommend", "you should buy", "you should invest", "is a good investment",
    "highly recommended", "best option for you", "i suggest investing"
]

def count_sentences(text):
    # Split by standard sentence terminators (. ! ?) followed by whitespace
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    # Filter out empty entries
    return len([s for s in sentences if s])

def is_grounded_and_compliant(answer, context_chunks):
    """
    Validates that the generated answer complies with all safety and length rules.
    Returns:
        tuple: (is_valid, validation_error_message)
    """
    # 1. Check sentence count constraint (<= 3 sentences)
    sentence_count = count_sentences(answer)
    if sentence_count > 3:
        logging.warning(f"Validation Failure: Answer has {sentence_count} sentences (max 3).")
        return False, "Answer exceeds the maximum length of 3 sentences."

    # 2. Check for advisory vocabulary
    answer_lower = answer.lower()
    for phrase in ADVISORY_TRIGGER_PHRASES:
        if phrase in answer_lower:
            logging.warning(f"Validation Failure: Advisory phrase '{phrase}' detected in generated answer.")
            return False, "Answer contains advisory language."

    # 3. Check for URLs or markdown links inside the answer body
    # Standard link pattern: [text](url) or http:// / https://
    url_pattern = re.compile(r"https?://[^\s]+|\[.*?\]\(.*?\)")
    if url_pattern.search(answer):
        logging.warning("Validation Failure: Output contains embedded URLs/links in body.")
        return False, "Answer contains unauthorized URLs or link structures."

    # 4. Basic grounding check (verify that key numbers mentioned in the answer exist in the context)
    # Extract numbers from the answer
    numbers_in_answer = re.findall(r"\d+(?:\.\d+)?%", answer)
    context_text = " ".join([chunk["text"] for chunk in context_chunks])
    
    for num in numbers_in_answer:
        if num not in context_text:
            logging.warning(f"Validation Failure: Number '{num}' generated by LLM is not grounded in context facts.")
            return False, f"Output contains ungrounded numeric metrics ('{num}')."

    return True, None

if __name__ == "__main__":
    # Test validator
    test_chunks = [{"text": "HDFC Mid Cap Fund Direct Growth exit load is 1% if redeemed within 1 year. Expense ratio is 0.73%."}]
    
    test_cases = [
        ("The exit load is 1% if redeemed within 1 year. The expense ratio is 0.73%.", True),
        ("The exit load is 1% if redeemed within 1 year. The expense ratio is 0.73%. It has been running since 2013. This is a very good fund.", False), # > 3 sentences
        ("I recommend HDFC Mid Cap Fund because the exit load is 1%.", False), # Advisory phrase
        ("The exit load is 2% if redeemed within 1 year.", False) # Ungrounded metric (2% not in context)
    ]

    print("\n--- Validator Verification ---")
    for text, expected in test_cases:
        valid, err = is_grounded_and_compliant(text, test_chunks)
        print(f"Text: {text}\nResult: Valid={valid}, Error={err} (Expected={expected})\n")
